### ISSUE TITLE
API is stopt working

### ISSUE THREAD

**Issue by smartthinks** [ashishtank/MMM-MercedesMe#5]
[https://developer.mercedes-benz.com/content-page/migration_2022](url)

Auth URL

old url: https://id.mercedes-benz.com/as/authorization.oauth2
new url: https://ssoalpha.dvb.corpinter.net/v1/auth
Token URL

old url: https://id.mercedes-benz.com/as/token.oauth2
new url: https://ssoalpha.dvb.corpinter.net/v1/token

Butt if I chance them in the node_help.js its still not working.

**Comment by ashishtank** [comment]
Hi 

This is work in progress. they did not only change the OAuth url but also changed the client app credentials and api scope requirements. I will update you once new version is available.

**Comment by Lukelumia** [comment]
I have created a Fix for this issue. Works for my Magic Mirror setup.

Please note I have fixed the singleDial as well & package.json

**Comment by ashishtank** [comment]
@smartthinks Please take latest branch and check if it works for you. I will update documentation to create new application in Mercedez website

**Comment by smartthinks** [comment]
Goodmorning, 

thanks for the update, but for me it's still not working. When I want to authorize (authenticate) then I get a error message. Bad request Invalid client_id ("910****) See picture

<img width="539" alt="Schermafbeelding 2022-12-07 om 11 57 48" src="https://user-images.githubusercontent.com/64124717/206162227-8f6aa493-1ac7-4386-b0f9-3ed5d13cee6c.png">

**Comment by smartthinks** [comment]
How di't you fix i't????

**Comment by smartthinks** [comment]
@Lukelumia
> I have created a Fix for this issue. Works for my Magic Mirror setup.
> 
> Please note I have fixed the singleDial as well & package.json

Please tell me How

**Comment by MarcinCh-81** [comment]
Hi, it seems I have an issue with Authentication call by the module. After clicking on 'Authenticate' I only get this:

<img width="374" alt="Screenshot 2024-10-23 141730" src="https://github.com/user-attachments/assets/086e64b8-205c-4d49-90c7-3668162a1ba4">

I would appreciate any suggestion on what might be causing this. Thank you in advance!
